export const chapters = [
  {
    id: 1,
    title: "Chapter 1: Quantitative Aptitude",
    subchapters: [
      { id: "number-system", title: "Number System" },
      { id: "lcm-hcf", title: "LCM & HCF" },
      { id: "percentages", title: "Percentages" },
      { id: "profit-loss", title: "Profit & Loss" },
      { id: "simple-compound-interest", title: "Simple & Compound Interest" },
      { id: "ratio-proportion", title: "Ratio & Proportion" },
      { id: "pipes-cisterns", title: "Pipes & Cisterns" },
      { id: "time-work", title: "Time & Work" },
      { id: "average", title: "Average" },
      { id: "permutations-combinations", title: "Permutations & Combinations" },
      { id: "probability", title: "Probability" },
      { id: "age-problems", title: "Age Problems" },
      { id: "partnerships", title: "Partnerships" },
      { id: "allegations-mixtures", title: "Allegations & Mixtures" },
      { id: "chain-rule", title: "Chain Rule" },
      { id: "train-problems", title: "Train Problems" },
      { id: "boats-streams", title: "Boats & Streams" },
      { id: "data-interpretation", title: "Data Interpretation" },
    ],
  },
  
  {
    id: 4,
    title: "Chapter 2: Logical Reasoning",
    subchapters: [
      { id: "number-series", title: "Number Series" },
      { id: "seating-arrangements", title: "Seating Arrangements" },
      { id: "clock-problems", title: "Clock Problems" },
      { id: "calendar", title: "Calendar" },
      { id: "blood-relations", title: "Blood Relations" },
      { id: "directions", title: "Directions" },
      { id: "word-pattern", title: "Word Pattern" },
      { id: "coding-decoding", title: "Coding & Decoding" },
      { id: "mathematical-operations", title: "Mathematical Operations" },
      { id: "venn-diagrams", title: "Venn Diagrams" },
      { id: "visual-reasoning", title: "Visual Reasoning" },
      { id: "paper-cutting-adding", title: "Paper Cutting & Adding" },
      { id: "cubes-dices", title: "Cubes & Dices" },
      { id: "data-sufficiency", title: "Data Sufficiency" },
    ],
    
  },
 
  {
    id: 7,
    title: "Chapter 3: Verbal Ability",
    subchapters: [
      { id: "reading-comprehension", title: "Reading Comprehension" },
      { id: "spotting-errors", title: "Spotting Errors" },
      { id: "sentence-formation", title: "Sentence Formation" },
      { id: "synonyms-antonyms", title: "Synonyms & Antonyms" },
      { id: "idioms-phrases", title: "Idioms & Phrases" },
    ],
  },
];