export const chapters = [
  {
    id: 1,
    title: "Chapter 1: Verbal Ability",
    subchapters: [
      { id: "reading-comprehension", title: "Reading Comprehension", noteId: "reading-comprehension" },
      { id: "spotting-errors", title: "Spotting Errors", noteId: "spotting-errors" },
      { id: "sentence-formation", title: "Sentence Formation", noteId: "sentence-formation" },
      { id: "synonyms-antonyms", title: "Synonyms & Antonyms", noteId: "synonyms-antonyms" },
      { id: "idioms-phrases", title: "Idioms & Phrases", noteId: "idioms-phrases" },
    ],
  },
  // FIX: Removed extra comma
  {
    id: 2,
    title: "Chapter 2: Logical Reasoning",
    subchapters: [
      { id: "number-series", title: "Number Series", noteId: "number-series" },
      { id: "seating-arrangements", title: "Seating Arrangements", noteId: "seating-arrangements" },
      { id: "clock-problems", title: "Clock Problems", noteId: "clock-problems" },
      { id: "calendar", title: "Calendar", noteId: "calendar" },
      { id: "blood-relations", title: "Blood Relations", noteId: "blood-relations" },
      { id: "directions", title: "Directions", noteId: "directions" },
      { id: "word-pattern", title: "Word Pattern", noteId: "word-pattern" },
      { id: "coding-decoding", title: "Coding & Decoding", noteId: "coding-decoding" },
      { id: "mathematical-operations", title: "Mathematical Operations", noteId: "mathematical-operations" },
      { id: "venn-diagrams", title: "Venn Diagrams", noteId: "venn-diagrams" },
      { id: "visual-reasoning", title: "Visual Reasoning", noteId: "visual-reasoning" },
      { id: "paper-cutting-adding", title: "Paper Cutting & Adding", noteId: "paper-cutting-adding" },
      { id: "cubes-dices", title: "Cubes & Dices", noteId: "cubes-dices" },
      { id: "data-sufficiency", title: "Data Sufficiency", noteId: "data-sufficiency" },
    ],
  },
  // FIX: Removed extra comma
  {
    id: 3,
    title: "Chapter 3: Quantitative Aptitude",
    subchapters: [
      { id: "number-system", title: "Number System", noteId: "number-system" },
      { id: "lcm-hcf", title: "LCM & HCF", noteId: "lcm-hcf" },
      { id: "percentages", title: "Percentages", noteId: "percentages" },
      { id: "profit-loss", title: "Profit & Loss", noteId: "profit-loss" },
      { id: "simple-compound-interest", title: "Simple & Compound Interest", noteId: "simple-compound-interest" },
      { id: "ratio-proportion", title: "Ratio & Proportion", noteId: "ratio-proportion" },
      { id: "pipes-cisterns", title: "Pipes & Cisterns", noteId: "pipes-cisterns" },
      { id: "time-work", title: "Time & Work", noteId: "time-work" },
      { id: "average", title: "Average", noteId: "average" },
      { id: "permutations-combinations", title: "Permutations & Combinations", noteId: "permutations-combinations" },
      { id: "probability", title: "Probability", noteId: "probability" },
      { id: "age-problems", title: "Age Problems", noteId: "age-problems" },
      { id: "partnerships", title: "Partnerships", noteId: "partnerships" },
      { id: "allegations-mixtures", title: "Allegations & Mixtures", noteId: "allegations-mixtures" },
      { id: "chain-rule", title: "Chain Rule", noteId: "chain-rule" },
      { id: "train-problems", title: "Train Problems", noteId: "train-problems" },
      { id: "boats-streams", title: "Boats & Streams", noteId: "boats-streams" },
      { id: "data-interpretation", title: "Data Interpretation", noteId: "data-interpretation" },
    ],
  },
];
// FIX: Removed extra '}'