
export const chapters = [
  {
    id: 1,
    title: "Chapter 1: Foundation & Setup",
    subchapters: [
      { id: "what-is-web-development", title: "What is Web Development?", noteId: "Chapter1", quizComponent: "Chapter1Quiz", practiceProblemComponent: "Chapter1Problem" },
      { id: "client-server-architecture", title: "Client-Server Architecture", noteId: "Chapter1", quizComponent: "Chapter1Quiz", practiceProblemComponent: "Chapter1Problem" },
      { id: "frontend-vs-backend", title: "Frontend vs Backend vs Full Stack", noteId: "Chapter1", quizComponent: "Chapter1Quiz", practiceProblemComponent: "Chapter1Problem" },
      { id: "intro-to-mern-stack", title: "Introduction to the MERN Stack", noteId: "Chapter1", quizComponent: "Chapter1Quiz", practiceProblemComponent: "Chapter1Problem" },
      { id: "dev-env-setup", title: "Development Environment Setup", noteId: "Chapter1", quizComponent: "Chapter1Quiz", practiceProblemComponent: "Chapter1Problem" },
      { id: "code-editors-extensions", title: "Code Editors & Extensions", noteId: "Chapter1", quizComponent: "Chapter1Quiz", practiceProblemComponent: "Chapter1Problem" },
      { id: "terminal-basics", title: "Terminal/Command Line Basics", noteId: "Chapter1", quizComponent: "Chapter1Quiz", practiceProblemComponent: "Chapter1Problem" },
    ],
  },
  {
    id: 2,
    title: "Chapter 2: Version Control with Git & GitHub",
    subchapters: [
      { id: "introduction-to-version-control", title: "2.1: Introduction to Version Control", noteId: "Chapter2", quizComponent: "Chapter2Quiz", practiceProblemComponent: "Chapter2Problem" },
      { id: "git-installation-configuration", title: "2.2: Git Installation & Configuration", noteId: "Chapter2", quizComponent: "Chapter2Quiz", practiceProblemComponent: "Chapter2Problem" },
      { id: "git-basics", title: "2.3: Git Basics (Init, Add, Commit, Status, Log)", noteId: "Chapter2", quizComponent: "Chapter2Quiz", practiceProblemComponent: "Chapter2Problem" },
      { id: "working-with-branches-merging", title: "2.4: Working with Branches & Merging", noteId: "Chapter2", quizComponent: "Chapter2Quiz", practiceProblemComponent: "Chapter2Problem" },
      { id: "github-introduction-account-setup", title: "2.5: GitHub Introduction & Account Setup", noteId: "Chapter2", quizComponent: "Chapter2Quiz", practiceProblemComponent: "Chapter2Problem" },
      { id: "remote-repositories", title: "2.6: Remote Repositories (Push, Pull, Clone, Fetch)", noteId: "Chapter2", quizComponent: "Chapter2Quiz", practiceProblemComponent: "Chapter2Problem" },
      { id: "collaboration-workflows", title: "2.7: Collaboration Workflows (Forks, Pull Requests, Issues)", noteId: "Chapter2", quizComponent: "Chapter2Quiz", practiceProblemComponent: "Chapter2Problem" },
      { id: "git-best-practices", title: "2.8: Git Best Practices & .gitignore", noteId: "Chapter2", quizComponent: "Chapter2Quiz", practiceProblemComponent: "Chapter2Problem" },
    ],
  },
  {
    id: 3,
    title: "Chapter 3: Frontend Fundamentals",
    subchapters: [
      { id: "html5-essentials", title: "3.1: HTML5 Essentials & Semantic Elements", noteId: "Chapter3", quizComponent: "Chapter3Quiz", practiceProblemComponent: "Chapter3Problem" },
      { id: "html-complete-guide", title: "3.2: HTML Complete Guide", noteId: "Chapter3", quizComponent: "Chapter3Quiz", practiceProblemComponent: "Chapter3Problem" },
      { id: "css3-complete-guide", title: "3.3: CSS3 Complete Guide", noteId: "Chapter3", quizComponent: "Chapter3Quiz", practiceProblemComponent: "Chapter3Problem" },
      { id: "css-layout", title: "3.4: CSS Layout (Flexbox & Grid)", noteId: "Chapter3", quizComponent: "Chapter3Quiz", practiceProblemComponent: "Chapter3Problem" },
      { id: "css-animations", title: "3.5: CSS Animations & Transitions", noteId: "Chapter3", quizComponent: "Chapter3Quiz", practiceProblemComponent: "Chapter3Problem" },
      { id: "responsive-design", title: "3.6: Responsive Design & Media Queries", noteId: "Chapter3", quizComponent: "Chapter3Quiz", practiceProblemComponent: "Chapter3Problem" },
      { id: "css-preprocessors", title: "3.7: CSS Preprocessors (Sass/SCSS)", noteId: "Chapter3", quizComponent: "Chapter3Quiz", practiceProblemComponent: "Chapter3Problem" },
      { id: "browser-developer-tools", title: "3.8: Browser Developer Tools", noteId: "Chapter3", quizComponent: "Chapter3Quiz", practiceProblemComponent: "Chapter3Problem" },
    ],
  },
  {
    id: 4,
    title: "Chapter 4: JavaScript Fundamentals",
    subchapters: [
      { id: "javascript-basics", title: "4.1: JavaScript Basics (Variables, Data Types, Operators)", noteId: "Chapter4", quizComponent: "Chapter4Quiz", practiceProblemComponent: "Chapter4Problem" },
      { id: "control-structures", title: "4.2: Control Structures (Conditionals, Loops)", noteId: "Chapter4", quizComponent: "Chapter4Quiz", practiceProblemComponent: "Chapter4Problem" },
      { id: "functions-scope", title: "4.3: Functions & Scope", noteId: "Chapter4", quizComponent: "Chapter4Quiz", practiceProblemComponent: "Chapter4Problem" },
      { id: "arrays-methods", title: "4.4: Arrays & Array Methods", noteId: "Chapter4", quizComponent: "Chapter4Quiz", practiceProblemComponent: "Chapter4Problem" },
      { id: "objects-methods", title: "4.5: Objects & Object Methods", noteId: "Chapter4", quizComponent: "Chapter4Quiz", practiceProblemComponent: "Chapter4Problem" },
      { id: "dom-manipulation-events", title: "4.6: DOM Manipulation & Events", noteId: "Chapter4", quizComponent: "Chapter4Quiz", practiceProblemComponent: "Chapter4Problem" },
      { id: "es6-features", title: "4.7: ES6+ Features (Arrow Functions, Destructuring, Modules)", noteId: "Chapter4", quizComponent: "Chapter4Quiz", practiceProblemComponent: "Chapter4Problem" },
      { id: "asynchronous-javascript", title: "4.8: Asynchronous JavaScript (Promises, Async/Await)", noteId: "Chapter4", quizComponent: "Chapter4Quiz", practiceProblemComponent: "Chapter4Problem" },
      { id: "error-handling-debugging", title: "4.9: Error Handling & Debugging", noteId: "Chapter4", quizComponent: "Chapter4Quiz", practiceProblemComponent: "Chapter4Problem" },
      { id: "js-miniproject", title: "4.10: Js-MiniProject(Stone,Paper,Scissor)", noteId: "Chapter4", quizComponent: "Chapter4Quiz", practiceProblemComponent: "Chapter4Problem" },
      { id: "mini-project-preview", title: "4.11: Mini Project Preview", noteId: "Chapter4", quizComponent: "Chapter4Quiz", practiceProblemComponent: "Chapter4Problem" },
    ],
  },
  {
    id: 5,
    title: "Chapter 5: CSS Frameworks & UI Libraries",
    subchapters: [
      { id: "introduction-to-css-frameworks", title: "5.1: Introduction to CSS Frameworks", noteId: "Chapter5", quizComponent: "Chapter5Quiz", practiceProblemComponent: "Chapter5Problem" },
      { id: "bootstrap-fundamentals", title: "5.2: Bootstrap Fundamentals", noteId: "Chapter5", quizComponent: "Chapter5Quiz", practiceProblemComponent: "Chapter5Problem" },
      { id: "tailwind-css-setup", title: "5.3: Tailwind CSS Setup & Configuration", noteId: "Chapter5", quizComponent: "Chapter5Quiz", practiceProblemComponent: "Chapter5Problem" },
      { id: "tailwind-css-utility-classes", title: "5.4: Tailwind CSS Utility Classes", noteId: "Chapter5", quizComponent: "Chapter5Quiz", practiceProblemComponent: "Chapter5Problem" },
      { id: "tailwind-css-responsive-design", title: "5.5: Tailwind CSS Responsive Design", noteId: "Chapter5", quizComponent: "Chapter5Quiz", practiceProblemComponent: "Chapter5Problem" },
      { id: "tailwind-css-components", title: "5.6: Tailwind CSS Components & Custom Styles", noteId: "Chapter5", quizComponent: "Chapter5Quiz", practiceProblemComponent: "Chapter5Problem" },
      { id: "css-framework-comparison", title: "5.7: CSS Framework Comparison & Best Practices", noteId: "Chapter5", quizComponent: "Chapter5Quiz", practiceProblemComponent: "Chapter5Problem" },
    ],
  },
  {
    id: 6,
    title: "Chapter 6: React.js - Frontend Framework",
    subchapters: [
      { id: "introduction-to-react", title: "6.1: Introduction to React & Virtual DOM", noteId: "Chapter6Part1", quizComponent: "Chapter6Quiz", practiceProblemComponent: "Chapter6Problem" },
      { id: "create-react-app", title: "6.2: Create React App & Project Structure", noteId: "Chapter6Part1", quizComponent: "Chapter6Quiz", practiceProblemComponent: "Chapter6Problem" },
      { id: "jsx-syntax", title: "6.3: JSX Syntax & Components", noteId: "Chapter6Part1", quizComponent: "Chapter6Quiz", practiceProblemComponent: "Chapter6Problem" },
      { id: "props-communication", title: "6.4: Props & Component Communication", noteId: "Chapter6Part1", quizComponent: "Chapter6Quiz", practiceProblemComponent: "Chapter6Problem" },
      { id: "state-management", title: "6.5: State Management with useState", noteId: "Chapter6Part1", quizComponent: "Chapter6Quiz", practiceProblemComponent: "Chapter6Problem" },
      { id: "event-handling", title: "6.6: Event Handling in React", noteId: "Chapter6Part1", quizComponent: "Chapter6Quiz", practiceProblemComponent: "Chapter6Problem" },
      { id: "conditional-rendering", title: "6.7: Conditional Rendering & Lists", noteId: "Chapter6Part2", quizComponent: "Chapter6Quiz", practiceProblemComponent: "Chapter6Problem" },
      { id: "react-hooks", title: "6.8: React Hooks (useEffect, useContext, useRef)", noteId: "Chapter6Part2", quizComponent: "Chapter6Quiz", practiceProblemComponent: "Chapter6Problem" },
      { id: "react-router", title: "6.9: React Router for Navigation", noteId: "Chapter6Part2", quizComponent: "Chapter6Quiz", practiceProblemComponent: "Chapter6Problem" },
      { id: "forms-validation", title: "6.10: Forms & Form Validation in React", noteId: "Chapter6Part2", quizComponent: "Chapter6Quiz", practiceProblemComponent: "Chapter6Problem" },
      { id: "component-lifecycle", title: "6.11: Component Lifecycle & Cleanup", noteId: "Chapter6Part2", quizComponent: "Chapter6Quiz", practiceProblemComponent: "Chapter6Problem" },
      { id: "react-mini-projects", title: "6.12: React Mini Projects", noteId: "Chapter6Part2", quizComponent: "Chapter6Quiz", practiceProblemComponent: "Chapter6Problem" },
    ],
  },
  {
    id: 7,
    title: "Chapter 7: Backend Development with Node.js",
    subchapters: [
      { id: "introduction-to-node", title: "7.1: Introduction to Node.js & Runtime Environment", noteId: "Chapter7", quizComponent: "Chapter7Quiz", practiceProblemComponent: "Chapter7Problem" },
      { id: "node-core-modules", title: "7.2: Node.js Core Modules (fs, path, http, url)", noteId: "Chapter7", quizComponent: "Chapter7Quiz", practiceProblemComponent: "Chapter7Problem" },
      { id: "npm-package-management", title: "7.3: npm & Package Management", noteId: "Chapter7", quizComponent: "Chapter7Quiz", practiceProblemComponent: "Chapter7Problem" },
      { id: "creating-node-server", title: "7.4: Creating Your First Node.js Server", noteId: "Chapter7", quizComponent: "Chapter7Quiz", practiceProblemComponent: "Chapter7Problem" },
      { id: "understanding-modules", title: "7.5: Understanding Modules & Module.exports", noteId: "Chapter7", quizComponent: "Chapter7Quiz", practiceProblemComponent: "Chapter7Problem" },
      { id: "asynchronous-programming-node", title: "7.6: Asynchronous Programming in Node.js", noteId: "Chapter7", quizComponent: "Chapter7Quiz", practiceProblemComponent: "Chapter7Problem" },
      { id: "file-system-operations", title: "7.7: File System Operations", noteId: "Chapter7", quizComponent: "Chapter7Quiz", practiceProblemComponent: "Chapter7Problem" },
      { id: "environment-variables", title: "7.8: Environment Variables & dotenv", noteId: "Chapter7", quizComponent: "Chapter7Quiz", practiceProblemComponent: "Chapter7Problem" },
    ],
  },
  {
    id: 8,
    title: "Chapter 8: Express.js - Backend Framework",
    subchapters: [
      { id: "introduction-to-express", title: "8.1: Introduction to Express.js", noteId: "Chapter8Part1", quizComponent: "Chapter8Quiz", practiceProblemComponent: "Chapter8Problem" },
      { id: "express-setup", title: "8.2: Express Setup & Basic Server", noteId: "Chapter8Part1", quizComponent: "Chapter8Quiz", practiceProblemComponent: "Chapter8Problem" },
      { id: "routing-parameters", title: "8.3: Routing & Route Parameters", noteId: "Chapter8Part1", quizComponent: "Chapter8Quiz", practiceProblemComponent: "Chapter8Problem" },
      { id: "middleware-concepts", title: "8.4: Middleware Concepts & Usage", noteId: "Chapter8Part1", quizComponent: "Chapter8Quiz", practiceProblemComponent: "Chapter8Problem" },
      { id: "built-in-middleware", title: "8.5: Built-in Middleware (express.json, express.static)", noteId: "Chapter8Part1", quizComponent: "Chapter8Quiz", practiceProblemComponent: "Chapter8Problem" },
      { id: "custom-middleware", title: "8.6: Custom Middleware Development", noteId: "Chapter8Part2", quizComponent: "Chapter8Quiz", practiceProblemComponent: "Chapter8Problem" },
      { id: "request-response-objects", title: "8.7: Request & Response Objects", noteId: "Chapter8Part2", quizComponent: "Chapter8Quiz", practiceProblemComponent: "Chapter8Problem" },
      { id: "error-handling-middleware", title: "8.8: Error Handling Middleware", noteId: "Chapter8Part2", quizComponent: "Chapter8Quiz", practiceProblemComponent: "Chapter8Problem" },
      { id: "express-router", title: "8.9: Express Router & Modular Routing", noteId: "Chapter8Part2", quizComponent: "Chapter8Quiz", practiceProblemComponent: "Chapter8Problem" },
      { id: "template-engines", title: "8.10: Template Engines (EJS, Handlebars)", noteId: "Chapter8Part2", quizComponent: "Chapter8Quiz", practiceProblemComponent: "Chapter8Problem" },
    ],
  },
  {
    id: 9,
    title: "Chapter 9: REST API Development",
    subchapters: [
      { id: "rest-principles", title: "9.1: REST Architecture Principles", noteId: "Chapter9Part1", quizComponent: "Chapter9Quiz", practiceProblemComponent: "Chapter9Problem" },
      { id: "http-methods", title: "9.2: HTTP Methods & Status Codes", noteId: "Chapter9Part1", quizComponent: "Chapter9Quiz", practiceProblemComponent: "Chapter9Problem" },
      { id: "api-design", title: "9.3: API Design Best Practices", noteId: "Chapter9Part1", quizComponent: "Chapter9Quiz", practiceProblemComponent: "Chapter9Problem" },
      { id: "crud-operations", title: "9.4: CRUD Operations Implementation", noteId: "Chapter9Part1", quizComponent: "Chapter9Quiz", practiceProblemComponent: "Chapter9Problem" },
      { id: "request-validation", title: "9.5: Request Validation & Sanitization", noteId: "Chapter9Part1", quizComponent: "Chapter9Quiz", practiceProblemComponent: "Chapter9Problem" },
      { id: "api-documentation", title: "9.6: API Documentation with Swagger/Postman", noteId: "Chapter9Part2", quizComponent: "Chapter9Quiz", practiceProblemComponent: "Chapter9Problem" },
      { id: "file-uploads", title: "9.7: File Uploads & Handling (Multer)", noteId: "Chapter9Part2", quizComponent: "Chapter9Quiz", practiceProblemComponent: "Chapter9Problem" },
      { id: "api-versioning", title: "9.8: API Versioning Strategies", noteId: "Chapter9Part2", quizComponent: "Chapter9Quiz", practiceProblemComponent: "Chapter9Problem" },
      { id: "rest-api-mini-project", title: "9.9: REST API Mini Project", noteId: "Chapter9Part2", quizComponent: "Chapter9Quiz", practiceProblemComponent: "Chapter9Problem" },
    ],
  },
  {
    id: 10,
    title: "Chapter 10: MongoDB - Database Layer",
    subchapters: [
      { id: "database-fundamentals", title: "10.1: Database Fundamentals (SQL vs NoSQL)", noteId: "Chapter10Part1", quizComponent: "Chapter10Quiz", practiceProblemComponent: "Chapter10Problem" },
      { id: "mongodb-introduction", title: "10.2: MongoDB Introduction & Installation", noteId: "Chapter10Part1", quizComponent: "Chapter10Quiz", practiceProblemComponent: "Chapter10Problem" },
      { id: "mongodb-compass", title: "10.3: MongoDB Compass & Shell Basics", noteId: "Chapter10Part1", quizComponent: "Chapter10Quiz", practiceProblemComponent: "Chapter10Problem" },
      { id: "mongodb-crud", title: "10.4: CRUD Operations in MongoDB", noteId: "Chapter10Part1", quizComponent: "Chapter10Quiz", practiceProblemComponent: "Chapter10Problem" },
      { id: "mongodb-data-types", title: "10.5: MongoDB Data Types & Schema Design", noteId: "Chapter10Part1", quizComponent: "Chapter10Quiz", practiceProblemComponent: "Chapter10Problem" },
      { id: "mongoose-introduction", title: "10.6: Mongoose ODM Introduction", noteId: "Chapter10Part1", quizComponent: "Chapter10Quiz", practiceProblemComponent: "Chapter10Problem" },
      { id: "mongoose-schemas", title: "10.7: Mongoose Schemas & Models", noteId: "Chapter10Part2", quizComponent: "Chapter10Quiz", practiceProblemComponent: "Chapter10Problem" },
      { id: "data-validation-mongoose", title: "10.8: Data Validation with Mongoose", noteId: "Chapter10Part2", quizComponent: "Chapter10Quiz", practiceProblemComponent: "Chapter10Problem" },
      { id: "data-relationships", title: "10.9: Data Relationships (Referenced & Embedded)", noteId: "Chapter10Part2", quizComponent: "Chapter10Quiz", practiceProblemComponent: "Chapter10Problem" },
      { id: "mongoose-middleware", title: "10.10: Mongoose Middleware & Hooks", noteId: "Chapter10Part2", quizComponent: "Chapter10Quiz", practiceProblemComponent: "Chapter10Problem" },
      { id: "indexing-query-optimization", title: "10.11: Indexing & Query Optimization", noteId: "Chapter10Part2", quizComponent: "Chapter10Quiz", practiceProblemComponent: "Chapter10Problem" },
      { id: "aggregation-pipeline", title: "10.12: Aggregation Pipeline Basics", noteId: "Chapter10Part2", quizComponent: "Chapter10Quiz", practiceProblemComponent: "Chapter10Problem" },
      { id: "database-mini-project", title: "10.13: Database Mini Project", noteId: "Chapter10Part2", quizComponent: "Chapter10Quiz", practiceProblemComponent: "Chapter10Problem" },
    ],
  },
];