export const practiceChapters = [
  {
    id: 1,
    title: "Chapter 1: Foundation & Setup Practice Problems",
    subchapters: [
      { id: "what-is-web-development", title: "What is Web Development? Practice Problems", practiceProblemId: "what-is-web-development" },
      { id: "client-server-architecture", title: "Client-Server Architecture Practice Problems", practiceProblemId: "client-server-architecture" },
      { id: "frontend-vs-backend", title: "Frontend vs Backend vs Full Stack Practice Problems", practiceProblemId: "frontend-vs-backend" },
      { id: "intro-to-mern-stack", title: "Introduction to the MERN Stack Practice Problems", practiceProblemId: "intro-to-mern-stack" },
      { id: "dev-env-setup", title: "Development Environment Setup Practice Problems", practiceProblemId: "dev-env-setup" },
      { id: "code-editors-extensions", title: "Code Editors & Extensions Practice Problems", practiceProblemId: "code-editors-extensions" },
      { id: "terminal-basics", title: "Terminal/Command Line Basics Practice Problems", practiceProblemId: "terminal-basics" },
    ],
  },
  {
    id: 2,
    title: "Chapter 2: Version Control with Git & GitHub Practice Problems",
    subchapters: [
      { id: "introduction-to-version-control", title: "2.1: Introduction to Version Control Practice Problems", practiceProblemId: "introduction-to-version-control" },
      { id: "git-installation-configuration", title: "2.2: Git Installation & Configuration Practice Problems", practiceProblemId: "git-installation-configuration" },
      { id: "git-basics", title: "2.3: Git Basics (Init, Add, Commit, Status, Log) Practice Problems", practiceProblemId: "git-basics" },
      { id: "working-with-branches-merging", title: "2.4: Working with Branches & Merging Practice Problems", practiceProblemId: "working-with-branches-merging" },
      { id: "github-introduction-account-setup", title: "2.5: GitHub Introduction & Account Setup Practice Problems", practiceProblemId: "github-introduction-account-setup" },
      { id: "remote-repositories", title: "2.6: Remote Repositories (Push, Pull, Clone, Fetch) Practice Problems", practiceProblemId: "remote-repositories" },
      { id: "collaboration-workflows", title: "2.7: Collaboration Workflows (Forks, Pull Requests, Issues) Practice Problems", practiceProblemId: "collaboration-workflows" },
      { id: "git-best-practices", title: "2.8: Git Best Practices & .gitignore Practice Problems", practiceProblemId: "git-best-practices" },
    ],
  },
  {
    id: 3,
    title: "Chapter 3: Frontend Fundamentals Practice Problems",
    subchapters: [
      { id: "html5-essentials", title: "3.1: HTML5 Essentials & Semantic Elements Practice Problems", practiceProblemId: "html5-essentials" },
      { id: "html-complete-guide", title: "3.2: HTML Complete Guide Practice Problems", practiceProblemId: "html-complete-guide" },
      { id: "css3-complete-guide", title: "3.3: CSS3 Complete Guide Practice Problems", practiceProblemId: "css3-complete-guide" },
      { id: "css-layout", title: "3.4: CSS Layout (Flexbox & Grid) Practice Problems", practiceProblemId: "css-layout" },
      { id: "css-animations", title: "3.5: CSS Animations & Transitions Practice Problems", practiceProblemId: "css-animations" },
      { id: "responsive-design", title: "3.6: Responsive Design & Media Queries Practice Problems", practiceProblemId: "responsive-design" },
      { id: "css-preprocessors", title: "3.7: CSS Preprocessors (Sass/SCSS) Practice Problems", practiceProblemId: "css-preprocessors" },
      { id: "browser-developer-tools", title: "3.8: Browser Developer Tools Practice Problems", practiceProblemId: "browser-developer-tools" },
    ],
  },
  {
    id: 4,
    title: "Chapter 4: JavaScript Fundamentals Practice Problems",
    subchapters: [
      { id: "javascript-basics", title: "4.1: JavaScript Basics (Variables, Data Types, Operators) Practice Problems", practiceProblemId: "javascript-basics" },
      { id: "control-structures", title: "4.2: Control Structures (Conditionals, Loops) Practice Problems", practiceProblemId: "control-structures" },
      { id: "functions-scope", title: "4.3: Functions & Scope Practice Problems", practiceProblemId: "functions-scope" },
      { id: "arrays-methods", title: "4.4: Arrays & Array Methods Practice Problems", practiceProblemId: "arrays-methods" },
      { id: "objects-methods", title: "4.5: Objects & Object Methods Practice Problems", practiceProblemId: "objects-methods" },
      { id: "dom-manipulation-events", title: "4.6: DOM Manipulation & Events Practice Problems", practiceProblemId: "dom-manipulation-events" },
      { id: "es6-features", title: "4.7: ES6+ Features (Arrow Functions, Destructuring, Modules) Practice Problems", practiceProblemId: "es6-features" },
      { id: "asynchronous-javascript", title: "4.8: Asynchronous JavaScript (Promises, Async/Await) Practice Problems", practiceProblemId: "asynchronous-javascript" },
      { id: "error-handling-debugging", title: "4.9: Error Handling & Debugging Practice Problems", practiceProblemId: "error-handling-debugging" },
      { id: "js-miniproject", title: "4.10: Js-MiniProject(Stone,Paper,Scissor) Practice Problems", practiceProblemId: "js-miniproject" },
      { id: "mini-project-preview", title: "4.11: Mini Project Preview Practice Problems", practiceProblemId: "mini-project-preview" },
    ],
  },
  {
    id: 5,
    title: "Chapter 5: CSS Frameworks & UI Libraries Practice Problems",
    subchapters: [
      { id: "introduction-to-css-frameworks", title: "5.1: Introduction to CSS Frameworks Practice Problems", practiceProblemId: "introduction-to-css-frameworks" },
      { id: "bootstrap-fundamentals", title: "5.2: Bootstrap Fundamentals Practice Problems", practiceProblemId: "bootstrap-fundamentals" },
      { id: "tailwind-css-setup", title: "5.3: Tailwind CSS Setup & Configuration Practice Problems", practiceProblemId: "tailwind-css-setup" },
      { id: "tailwind-css-utility-classes", title: "5.4: Tailwind CSS Utility Classes Practice Problems", practiceProblemId: "tailwind-css-utility-classes" },
      { id: "tailwind-css-responsive-design", title: "5.5: Tailwind CSS Responsive Design Practice Problems", practiceProblemId: "tailwind-css-responsive-design" },
      { id: "tailwind-css-components", title: "5.6: Tailwind CSS Components & Custom Styles Practice Problems", practiceProblemId: "tailwind-css-components" },
      { id: "css-framework-comparison", title: "5.7: CSS Framework Comparison & Best Practices Practice Problems", practiceProblemId: "css-framework-comparison" },
    ],
  },
  {
    id: 6,
    title: "Chapter 6: React.js - Frontend Framework Practice Problems",
    subchapters: [
      { id: "introduction-to-react", title: "6.1: Introduction to React & Virtual DOM Practice Problems", practiceProblemId: "introduction-to-react" },
      { id: "create-react-app", title: "6.2: Create React App & Project Structure Practice Problems", practiceProblemId: "create-react-app" },
      { id: "jsx-syntax", title: "6.3: JSX Syntax & Components Practice Problems", practiceProblemId: "jsx-syntax" },
      { id: "props-communication", title: "6.4: Props & Component Communication Practice Problems", practiceProblemId: "props-communication" },
      { id: "state-management", title: "6.5: State Management with useState Practice Problems", practiceProblemId: "state-management" },
      { id: "event-handling", title: "6.6: Event Handling in React Practice Problems", practiceProblemId: "event-handling" },
      { id: "conditional-rendering", title: "6.7: Conditional Rendering & Lists Practice Problems", practiceProblemId: "conditional-rendering" },
      { id: "react-hooks", title: "6.8: React Hooks (useEffect, useContext, useRef) Practice Problems", practiceProblemId: "react-hooks" },
      { id: "react-router", title: "6.9: React Router for Navigation Practice Problems", practiceProblemId: "react-router" },
      { id: "forms-validation", title: "6.10: Forms & Form Validation in React Practice Problems", practiceProblemId: "forms-validation" },
      { id: "component-lifecycle", title: "6.11: Component Lifecycle & Cleanup Practice Problems", practiceProblemId: "component-lifecycle" },
      { id: "react-mini-projects", title: "6.12: React Mini Projects Practice Problems", practiceProblemId: "react-mini-projects" },
    ],
  },
  {
    id: 7,
    title: "Chapter 7: Backend Development with Node.js Practice Problems",
    subchapters: [
      { id: "introduction-to-node", title: "7.1: Introduction to Node.js & Runtime Environment Practice Problems", practiceProblemId: "introduction-to-node" },
      { id: "node-core-modules", title: "7.2: Node.js Core Modules (fs, path, http, url) Practice Problems", practiceProblemId: "node-core-modules" },
      { id: "npm-package-management", title: "7.3: npm & Package Management Practice Problems", practiceProblemId: "npm-package-management" },
      { id: "creating-node-server", title: "7.4: Creating Your First Node.js Server Practice Problems", practiceProblemId: "creating-node-server" },
      { id: "understanding-modules", title: "7.5: Understanding Modules & Module.exports Practice Problems", practiceProblemId: "understanding-modules" },
      { id: "asynchronous-programming-node", title: "7.6: Asynchronous Programming in Node.js Practice Problems", practiceProblemId: "asynchronous-programming-node" },
      { id: "file-system-operations", title: "7.7: File System Operations Practice Problems", practiceProblemId: "file-system-operations" },
      { id: "environment-variables", title: "7.8: Environment Variables & dotenv Practice Problems", practiceProblemId: "environment-variables" },
    ],
  },
  {
    id: 8,
    title: "Chapter 8: Express.js - Backend Framework Practice Problems",
    subchapters: [
      { id: "introduction-to-express", title: "8.1: Introduction to Express.js Practice Problems", practiceProblemId: "introduction-to-express" },
      { id: "express-setup", title: "8.2: Express Setup & Basic Server Practice Problems", practiceProblemId: "express-setup" },
      { id: "routing-parameters", title: "8.3: Routing & Route Parameters Practice Problems", practiceProblemId: "routing-parameters" },
      { id: "middleware-concepts", title: "8.4: Middleware Concepts & Usage Practice Problems", practiceProblemId: "middleware-concepts" },
      { id: "built-in-middleware", title: "8.5: Built-in Middleware (express.json, express.static) Practice Problems", practiceProblemId: "built-in-middleware" },
      { id: "custom-middleware", title: "8.6: Custom Middleware Development Practice Problems", practiceProblemId: "custom-middleware" },
      { id: "request-response-objects", title: "8.7: Request & Response Objects Practice Problems", practiceProblemId: "request-response-objects" },
      { id: "error-handling-middleware", title: "8.8: Error Handling Middleware Practice Problems", practiceProblemId: "error-handling-middleware" },
      { id: "express-router", title: "8.9: Express Router & Modular Routing Practice Problems", practiceProblemId: "express-router" },
      { id: "template-engines", title: "8.10: Template Engines (EJS, Handlebars) Practice Problems", practiceProblemId: "template-engines" },
    ],
  },
  {
    id: 9,
    title: "Chapter 9: REST API Development Practice Problems",
    subchapters: [
      { id: "rest-principles", title: "9.1: REST Architecture Principles Practice Problems", practiceProblemId: "rest-principles" },
      { id: "http-methods", title: "9.2: HTTP Methods & Status Codes Practice Problems", practiceProblemId: "http-methods" },
      { id: "api-design", title: "9.3: API Design Best Practices Practice Problems", practiceProblemId: "api-design" },
      { id: "crud-operations", title: "9.4: CRUD Operations Implementation Practice Problems", practiceProblemId: "crud-operations" },
      { id: "request-validation", title: "9.5: Request Validation & Sanitization Practice Problems", practiceProblemId: "request-validation" },
      { id: "api-documentation", title: "9.6: API Documentation with Swagger/Postman Practice Problems", practiceProblemId: "api-documentation" },
      { id: "file-uploads", title: "9.7: File Uploads & Handling (Multer) Practice Problems", practiceProblemId: "file-uploads" },
      { id: "api-versioning", title: "9.8: API Versioning Strategies Practice Problems", practiceProblemId: "api-versioning" },
      { id: "rest-api-mini-project", title: "9.9: REST API Mini Project Practice Problems", practiceProblemId: "rest-api-mini-project" },
    ],
  },
  {
    id: 10,
    title: "Chapter 10: MongoDB - Database Layer Practice Problems",
    subchapters: [
      { id: "database-fundamentals", title: "10.1: Database Fundamentals (SQL vs NoSQL) Practice Problems", practiceProblemId: "database-fundamentals" },
      { id: "mongodb-introduction", title: "10.2: MongoDB Introduction & Installation Practice Problems", practiceProblemId: "mongodb-introduction" },
      { id: "mongodb-compass", title: "10.3: MongoDB Compass & Shell Basics Practice Problems", practiceProblemId: "mongodb-compass" },
      { id: "mongodb-crud", title: "10.4: CRUD Operations in MongoDB Practice Problems", practiceProblemId: "mongodb-crud" },
      { id: "mongodb-data-types", title: "10.5: MongoDB Data Types & Schema Design Practice Problems", practiceProblemId: "mongodb-data-types" },
      { id: "mongoose-introduction", title: "10.6: Mongoose ODM Introduction Practice Problems", practiceProblemId: "mongoose-introduction" },
      { id: "mongoose-schemas", title: "10.7: Mongoose Schemas & Models Practice Problems", practiceProblemId: "mongoose-schemas" },
      { id: "data-validation-mongoose", title: "10.8: Data Validation with Mongoose Practice Problems", practiceProblemId: "data-validation-mongoose" },
      { id: "data-relationships", title: "10.9: Data Relationships (Referenced & Embedded) Practice Problems", practiceProblemId: "data-relationships" },
      { id: "mongoose-middleware", title: "10.10: Mongoose Middleware & Hooks Practice Problems", practiceProblemId: "mongoose-middleware" },
      { id: "indexing-query-optimization", title: "10.11: Indexing & Query Optimization Practice Problems", practiceProblemId: "indexing-query-optimization" },
      { id: "aggregation-pipeline", title: "10.12: Aggregation Pipeline Basics Practice Problems", practiceProblemId: "aggregation-pipeline" },
      { id: "database-mini-project", title: "10.13: Database Mini Project Practice Problems", practiceProblemId: "database-mini-project" },
    ],
  },
];