export const quizChapters = [
  {
    id: 1,
    title: "Chapter 1: Foundation & Setup Quizzes",
    subchapters: [
      { id: "what-is-web-development", title: "What is Web Development? Quiz", quizId: "what-is-web-development" },
      { id: "client-server-architecture", title: "Client-Server Architecture Quiz", quizId: "client-server-architecture" },
      { id: "frontend-vs-backend", title: "Frontend vs Backend vs Full Stack Quiz", quizId: "frontend-vs-backend" },
      { id: "intro-to-mern-stack", title: "Introduction to the MERN Stack Quiz", quizId: "intro-to-mern-stack" },
      { id: "dev-env-setup", title: "Development Environment Setup Quiz", quizId: "dev-env-setup" },
      { id: "code-editors-extensions", title: "Code Editors & Extensions Quiz", quizId: "code-editors-extensions" },
      { id: "terminal-basics", title: "Terminal/Command Line Basics Quiz", quizId: "terminal-basics" },
    ],
  },
  {
    id: 2,
    title: "Chapter 2: Version Control with Git & GitHub Quizzes",
    subchapters: [
      { id: "introduction-to-version-control", title: "2.1: Introduction to Version Control Quiz", quizId: "introduction-to-version-control" },
      { id: "git-installation-configuration", title: "2.2: Git Installation & Configuration Quiz", quizId: "git-installation-configuration" },
      { id: "git-basics", title: "2.3: Git Basics (Init, Add, Commit, Status, Log) Quiz", quizId: "git-basics" },
      { id: "working-with-branches-merging", title: "2.4: Working with Branches & Merging Quiz", quizId: "working-with-branches-merging" },
      { id: "github-introduction-account-setup", title: "2.5: GitHub Introduction & Account Setup Quiz", quizId: "github-introduction-account-setup" },
      { id: "remote-repositories", title: "2.6: Remote Repositories (Push, Pull, Clone, Fetch) Quiz", quizId: "remote-repositories" },
      { id: "collaboration-workflows", title: "2.7: Collaboration Workflows (Forks, Pull Requests, Issues) Quiz", quizId: "collaboration-workflows" },
      { id: "git-best-practices", title: "2.8: Git Best Practices & .gitignore Quiz", quizId: "git-best-practices" },
    ],
  },
  {
    id: 3,
    title: "Chapter 3: Frontend Fundamentals Quizzes",
    subchapters: [
      { id: "html5-essentials", title: "3.1: HTML5 Essentials & Semantic Elements Quiz", quizId: "html5-essentials" },
      { id: "html-complete-guide", title: "3.2: HTML Complete Guide Quiz", quizId: "html-complete-guide" },
      { id: "css3-complete-guide", title: "3.3: CSS3 Complete Guide Quiz", quizId: "css3-complete-guide" },
      { id: "css-layout", title: "3.4: CSS Layout (Flexbox & Grid) Quiz", quizId: "css-layout" },
      { id: "css-animations", title: "3.5: CSS Animations & Transitions Quiz", quizId: "css-animations" },
      { id: "responsive-design", title: "3.6: Responsive Design & Media Queries Quiz", quizId: "responsive-design" },
      { id: "css-preprocessors", title: "3.7: CSS Preprocessors (Sass/SCSS) Quiz", quizId: "css-preprocessors" },
      { id: "browser-developer-tools", title: "3.8: Browser Developer Tools Quiz", quizId: "browser-developer-tools" },
    ],
  },
  {
    id: 4,
    title: "Chapter 4: JavaScript Fundamentals Quizzes",
    subchapters: [
      { id: "javascript-basics", title: "4.1: JavaScript Basics (Variables, Data Types, Operators) Quiz", quizId: "javascript-basics" },
      { id: "control-structures", title: "4.2: Control Structures (Conditionals, Loops) Quiz", quizId: "control-structures" },
      { id: "functions-scope", title: "4.3: Functions & Scope Quiz", quizId: "functions-scope" },
      { id: "arrays-methods", title: "4.4: Arrays & Array Methods Quiz", quizId: "arrays-methods" },
      { id: "objects-methods", title: "4.5: Objects & Object Methods Quiz", quizId: "objects-methods" },
      { id: "dom-manipulation-events", title: "4.6: DOM Manipulation & Events Quiz", quizId: "dom-manipulation-events" },
      { id: "es6-features", title: "4.7: ES6+ Features (Arrow Functions, Destructuring, Modules) Quiz", quizId: "es6-features" },
      { id: "asynchronous-javascript", title: "4.8: Asynchronous JavaScript (Promises, Async/Await) Quiz", quizId: "asynchronous-javascript" },
      { id: "error-handling-debugging", title: "4.9: Error Handling & Debugging Quiz", quizId: "error-handling-debugging" },
      { id: "js-miniproject", title: "4.10: Js-MiniProject(Stone,Paper,Scissor) Quiz", quizId: "js-miniproject" },
      { id: "mini-project-preview", title: "4.11: Mini Project Preview Quiz", quizId: "mini-project-preview" },
    ],
  },
  {
    id: 5,
    title: "Chapter 5: CSS Frameworks & UI Libraries Quizzes",
    subchapters: [
      { id: "introduction-to-css-frameworks", title: "5.1: Introduction to CSS Frameworks Quiz", quizId: "introduction-to-css-frameworks" },
      { id: "bootstrap-fundamentals", title: "5.2: Bootstrap Fundamentals Quiz", quizId: "bootstrap-fundamentals" },
      { id: "tailwind-css-setup", title: "5.3: Tailwind CSS Setup & Configuration Quiz", quizId: "tailwind-css-setup" },
      { id: "tailwind-css-utility-classes", title: "5.4: Tailwind CSS Utility Classes Quiz", quizId: "tailwind-css-utility-classes" },
      { id: "tailwind-css-responsive-design", title: "5.5: Tailwind CSS Responsive Design Quiz", quizId: "tailwind-css-responsive-design" },
      { id: "tailwind-css-components", title: "5.6: Tailwind CSS Components & Custom Styles Quiz", quizId: "tailwind-css-components" },
      { id: "css-framework-comparison", title: "5.7: CSS Framework Comparison & Best Practices Quiz", quizId: "css-framework-comparison" },
    ],
  },
  {
    id: 6,
    title: "Chapter 6: React.js - Frontend Framework Quizzes",
    subchapters: [
      { id: "introduction-to-react", title: "6.1: Introduction to React & Virtual DOM Quiz", quizId: "introduction-to-react" },
      { id: "create-react-app", title: "6.2: Create React App & Project Structure Quiz", quizId: "create-react-app" },
      { id: "jsx-syntax", title: "6.3: JSX Syntax & Components Quiz", quizId: "jsx-syntax" },
      { id: "props-communication", title: "6.4: Props & Component Communication Quiz", quizId: "props-communication" },
      { id: "state-management", title: "6.5: State Management with useState Quiz", quizId: "state-management" },
      { id: "event-handling", title: "6.6: Event Handling in React Quiz", quizId: "event-handling" },
      { id: "conditional-rendering", title: "6.7: Conditional Rendering & Lists Quiz", quizId: "conditional-rendering" },
      { id: "react-hooks", title: "6.8: React Hooks (useEffect, useContext, useRef) Quiz", quizId: "react-hooks" },
      { id: "react-router", title: "6.9: React Router for Navigation Quiz", quizId: "react-router" },
      { id: "forms-validation", title: "6.10: Forms & Form Validation in React Quiz", quizId: "forms-validation" },
      { id: "component-lifecycle", title: "6.11: Component Lifecycle & Cleanup Quiz", quizId: "component-lifecycle" },
      { id: "react-mini-projects", title: "6.12: React Mini Projects Quiz", quizId: "react-mini-projects" },
    ],
  },
  {
    id: 7,
    title: "Chapter 7: Backend Development with Node.js Quizzes",
    subchapters: [
      { id: "introduction-to-node", title: "7.1: Introduction to Node.js & Runtime Environment Quiz", quizId: "introduction-to-node" },
      { id: "node-core-modules", title: "7.2: Node.js Core Modules (fs, path, http, url) Quiz", quizId: "node-core-modules" },
      { id: "npm-package-management", title: "7.3: npm & Package Management Quiz", quizId: "npm-package-management" },
      { id: "creating-node-server", title: "7.4: Creating Your First Node.js Server Quiz", quizId: "creating-node-server" },
      { id: "understanding-modules", title: "7.5: Understanding Modules & Module.exports Quiz", quizId: "understanding-modules" },
      { id: "asynchronous-programming-node", title: "7.6: Asynchronous Programming in Node.js Quiz", quizId: "asynchronous-programming-node" },
      { id: "file-system-operations", title: "7.7: File System Operations Quiz", quizId: "file-system-operations" },
      { id: "environment-variables", title: "7.8: Environment Variables & dotenv Quiz", quizId: "environment-variables" },
    ],
  },
  {
    id: 8,
    title: "Chapter 8: Express.js - Backend Framework Quizzes",
    subchapters: [
      { id: "introduction-to-express", title: "8.1: Introduction to Express.js Quiz", quizId: "introduction-to-express" },
      { id: "express-setup", title: "8.2: Express Setup & Basic Server Quiz", quizId: "express-setup" },
      { id: "routing-parameters", title: "8.3: Routing & Route Parameters Quiz", quizId: "routing-parameters" },
      { id: "middleware-concepts", title: "8.4: Middleware Concepts & Usage Quiz", quizId: "middleware-concepts" },
      { id: "built-in-middleware", title: "8.5: Built-in Middleware (express.json, express.static) Quiz", quizId: "built-in-middleware" },
      { id: "custom-middleware", title: "8.6: Custom Middleware Development Quiz", quizId: "custom-middleware" },
      { id: "request-response-objects", title: "8.7: Request & Response Objects Quiz", quizId: "request-response-objects" },
      { id: "error-handling-middleware", title: "8.8: Error Handling Middleware Quiz", quizId: "error-handling-middleware" },
      { id: "express-router", title: "8.9: Express Router & Modular Routing Quiz", quizId: "express-router" },
      { id: "template-engines", title: "8.10: Template Engines (EJS, Handlebars) Quiz", quizId: "template-engines" },
    ],
  },
  {
    id: 9,
    title: "Chapter 9: REST API Development Quizzes",
    subchapters: [
      { id: "rest-principles", title: "9.1: REST Architecture Principles Quiz", quizId: "rest-principles" },
      { id: "http-methods", title: "9.2: HTTP Methods & Status Codes Quiz", quizId: "http-methods" },
      { id: "api-design", title: "9.3: API Design Best Practices Quiz", quizId: "api-design" },
      { id: "crud-operations", title: "9.4: CRUD Operations Implementation Quiz", quizId: "crud-operations" },
      { id: "request-validation", title: "9.5: Request Validation & Sanitization Quiz", quizId: "request-validation" },
      { id: "api-documentation", title: "9.6: API Documentation with Swagger/Postman Quiz", quizId: "api-documentation" },
      { id: "file-uploads", title: "9.7: File Uploads & Handling (Multer) Quiz", quizId: "file-uploads" },
      { id: "api-versioning", title: "9.8: API Versioning Strategies Quiz", quizId: "api-versioning" },
      { id: "rest-api-mini-project", title: "9.9: REST API Mini Project Quiz", quizId: "rest-api-mini-project" },
    ],
  },
  {
    id: 10,
    title: "Chapter 10: MongoDB - Database Layer Quizzes",
    subchapters: [
      { id: "database-fundamentals", title: "10.1: Database Fundamentals (SQL vs NoSQL) Quiz", quizId: "database-fundamentals" },
      { id: "mongodb-introduction", title: "10.2: MongoDB Introduction & Installation Quiz", quizId: "mongodb-introduction" },
      { id: "mongodb-compass", title: "10.3: MongoDB Compass & Shell Basics Quiz", quizId: "mongodb-compass" },
      { id: "mongodb-crud", title: "10.4: CRUD Operations in MongoDB Quiz", quizId: "mongodb-crud" },
      { id: "mongodb-data-types", title: "10.5: MongoDB Data Types & Schema Design Quiz", quizId: "mongodb-data-types" },
      { id: "mongoose-introduction", title: "10.6: Mongoose ODM Introduction Quiz", quizId: "mongoose-introduction" },
      { id: "mongoose-schemas", title: "10.7: Mongoose Schemas & Models Quiz", quizId: "mongoose-schemas" },
      { id: "data-validation-mongoose", title: "10.8: Data Validation with Mongoose Quiz", quizId: "data-validation-mongoose" },
      { id: "data-relationships", title: "10.9: Data Relationships (Referenced & Embedded) Quiz", quizId: "data-relationships" },
      { id: "mongoose-middleware", title: "10.10: Mongoose Middleware & Hooks Quiz", quizId: "mongoose-middleware" },
      { id: "indexing-query-optimization", title: "10.11: Indexing & Query Optimization Quiz", quizId: "indexing-query-optimization" },
      { id: "aggregation-pipeline", title: "10.12: Aggregation Pipeline Basics Quiz", quizId: "aggregation-pipeline" },
      { id: "database-mini-project", title: "10.13: Database Mini Project Quiz", quizId: "database-mini-project" },
    ],
  },
];